spring:
  application:
    name: desafio-cep
  datasource:
    url: jdbc:h2:mem:cepdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

cep:
  provider:
    base-url: http://localhost:8081

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: desafio-cep
    description: Consulta de CEP com log em banco (arquitetura hexagonal)
    version: 1.0.0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.example.cep: INFO
